#!/usr/bin/python3
# Generate c-file and matching .h file from a text file by appending \n and enclosing in double quotes.
# It would be good to strip comments, both html and JavaScript, to reduce image size.
# And maybe collapse white-space.

import hashlib
import os
import re
import sys

infilename = sys.argv[1]
base, ext = os.path.splitext(infilename)

js_comment_re = re.compile(r' *//[^\n]*')
html_comment_re = re.compile(r'<!--.*?-->', re.DOTALL)
multi_space_re = re.compile(r' +')
multi_newline_re = re.compile(r'\n\n+')
hex_value_re = re.compile(r'\\x')
escaped_quote_re = re.compile(r"\\'")

text = open(infilename).read()

text = js_comment_re.sub('', text)
text = html_comment_re.sub('', text)
text = multi_space_re.sub(' ', text)
text = multi_newline_re.sub(r'\n', text)
text = hex_value_re.sub(r'\\\\x', text)
text = escaped_quote_re.sub(r"\\\\'", text)

etag = hashlib.md5(text.encode('UTF8')).hexdigest()

with open(base + '_html.c', 'w') as f:
    f.write('char %s_etag[] = "%s";\nchar %s_html[] =\n' % (base, etag, base))
    for l in text.split('\n'):
        f.write('  "%s\\n"\n' % (l,))
    f.write('  ;\n')
open(base + '_html.h', 'w').write('extern char %s_etag[];\nextern char %s_html[];\n' % (base, base,))
