#!/usr/bin/bash

# extract assessRelayState and its requirements, wrap it in a main() that simulates the rest of the program.

sed '/^int main/,$ d' simwrapper.c >sim.cpp
sed -n -e '/^static[^(]*$/ p' \
       -e '/^extern /p' \
       -e '/^#define /p' \
       -e '/^const char /p' \
       -e '/^enum PERIOD_STATE/p' \
       -e '/^typedef/p' \
       -e '/^static int8_t assessRelayState/,/^}$/ p' \
       -e '/^float normalizeTemperature/,/^}$/ p' \
       -e '/^static void handlePeaksAndTroughs/,/^}$/ p' \
       -e '/^static void assessPerformance/,/^}$/ p' \
       -e '/^static void setIfImpossible/,/^}$/ p' \
       -e '/^static void recordSwitchedOn/,/^}$/ p' \
       -e '/^static void recordSwitchedOff/,/^}$/ p' \
       ../thermostat.ino | grep -v 'static.*millis_now' >>sim.cpp
sed -n '/^int main/,$ p' simwrapper.c >>sim.cpp

cat <<EnD >globals.h
#include <iostream>
enum RELAY_STATE {POWER_OFF, POWER_ON};
static int8_t assessRelayState(int8_t pre_relay_state);
float normalizeTemperature(float temperature);
#define DOPRINT(x) std::cerr << (x)
#define DOPRINTLN(x) {DOPRINT(x); std::cerr << "\n"; }
EnD
grep -v -e 'Arduino.h' -e 'DOPRINT' ../globals.h >>globals.h
cp ../globals.c globals.cpp

g++ -w -fpermissive -I $PWD -o /tmp/sim sim.cpp globals.cpp
